project:
  type: website

website:
  title: "Binchen's Tech Blog"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Posts
        href: posts/
      - text: About
        href: about.qmd
  page-footer:
    left: "© 2025 Binchen Chen"
    right: "Built with Quarto"

format:
  html:
    theme: cosmo
    toc: true
    toc-location: left
    toc-depth: 3
    page-layout: full
    code-fold: true
    code-tools: true
    fig-cap-location: bottom
    number-sections: true
    css: styles.css

collections:
  posts:
    categories: true
    tags: true
    exclude:
      - index.qmd
      - about.qmd
    listing:
      sort-by: date
      sort-descending: true
      fields: [title, date, categories, tags, description]
      contents: false